//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelfServiceReceptionist.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorMeeting
    {
        public System.Guid VisitorMeetingID { get; set; }
        public Nullable<System.Guid> MeetingID { get; set; }
        public Nullable<System.Guid> VisitorID { get; set; }
    
        public virtual Meeting Meeting { get; set; }
        public virtual Visitor Visitor { get; set; }
    }
}
